In [49]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [50]:
# import numpy libray
import numpy as np

In [51]:
#use 1D-list in numpy array
arr = np.array(my_list)

In [52]:
arr

array([1, 2, 3])

In [53]:
my_mat = [[12,24,36],[45,56,39],[37,48,32]]

In [54]:
#use 2D-list in numpy array
np.array(my_mat)

array([[12, 24, 36],
       [45, 56, 39],
       [37, 48, 32]])

In [55]:
#use arrange method
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#use arrange method using start and end point
np.arange(3,12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
#use arrange method using gap point
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [59]:
#use zeros method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])