In [49]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [50]:
# import numpy libray
import numpy as np

In [51]:
#use 1D-list in numpy array
arr = np.array(my_list)

In [52]:
arr

array([1, 2, 3])

In [53]:
my_mat = [[12,24,36],[45,56,39],[37,48,32]]

In [54]:
#use 2D-list in numpy array
np.array(my_mat)

array([[12, 24, 36],
       [45, 56, 39],
       [37, 48, 32]])

In [55]:
#use arrange method
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#use arrange method using start and end point
np.arange(3,12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
#use arrange method using gap point
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [59]:
#use zeros method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
#use ones method
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [62]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [66]:
#use linspace method, 3rd attribute use for limit 
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [67]:
#use identity matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [73]:
#random function
#rand function return float from 0 to 1
np.random.rand(10)
np.random.rand(3,4)

array([[0.66126287, 0.78031769, 0.09887693, 0.32046305],
       [0.83180558, 0.93841966, 0.2056512 , 0.93115172],
       [0.6685845 , 0.26751775, 0.63854192, 0.22307799]])

In [75]:
#randn function retrun standard normal
np.random.randn(10)
np.random.randn(3,4)

array([[-1.14734527,  0.01727961,  0.05440089,  0.03342352],
       [ 2.1943944 ,  3.54750884,  2.43404681, -1.12705297],
       [-1.13156267, -0.01052987, -0.95992458,  0.77916394]])

In [95]:
#randint return random integer number from start to end limit, it doesn't include end value
randarr = np.random.randint(15,50,10)

In [96]:
randarr

array([21, 20, 45, 31, 29, 34, 24, 22, 17, 42])

In [122]:
randarr.max()

45

In [123]:
randarr.min()

17

In [124]:
randarr.dtype

dtype('int64')

In [125]:
#array reshape method change the shape of array without changing the data
#make sure arrange limit should not exceed from array limit
arr = np.arange(12)
arr.reshape(2,6)
arr.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [120]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
arr.shape

(3, 4)