In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Indexing of numpy array
arr[6]

6

In [6]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
# Broadcast Numpy array
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# While broadcast it override the original array
slice_arr = arr[0:6]
slice_arr[:] = 99
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
# While broadcast if we do not want the original array override
arr_new = np.arange(4,17)
copy_new_arr = arr_new.copy()
copy_new_arr[:]= 101
copy_new_arr

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [20]:
# Original array stays as it is
arr_new

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [28]:
#Grab the element from 2D array
arr_2d = np.array([[2,4,6],[20,29,11],[28,11,23]])
arr_2d

array([[ 2,  4,  6],
       [20, 29, 11],
       [28, 11, 23]])

In [29]:
arr_2d[2,1]

11

In [34]:
arr_2d[:2,1:]

array([[ 4,  6],
       [29, 11]])

In [36]:
# Mostly use in ML
arr_2d[:,2:]

array([[ 6],
       [11],
       [23]])

In [38]:
#Condition selection
arr = np.arange(4,12)
bool_arr= arr > 8
bool_arr

array([False, False, False, False, False,  True,  True,  True])

In [39]:
arr[bool_arr]

array([ 9, 10, 11])

In [40]:
arr[arr > 6]

array([ 7,  8,  9, 10, 11])

In [46]:
arr_2d = np.arange(60).reshape(6,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [47]:
#Practice required
arr_2d[3:5,5:7]

array([[35, 36],
       [45, 46]])